"""empty message

Revision ID: 802c808c9804
Revises: 03cd64b9a0e3
Create Date: 2024-03-04 18:38:47.315489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802c808c9804'
down_revision = '03cd64b9a0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')


    # ### end Alembic commands ###
